notifications:
  email:
    on_success: never
    on_failure: always
matrix:
  include:
    - os: linux
      language: python
      python:
        - "3.8"
      before_install:
        - wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz
        - tar xvfz libsodium-1.0.18.tar.gz
        - cd libsodium-1.0.18
        - sudo ./configure
        - sudo make
        - sudo make install
        - sudo ldconfig
        - cd ..
      install:
        - pip install pylint
        - pip install .
script:
  - pylint oblivious
  - nosetests
