[project]
name = "oblivious"
version = "7.0.0"
description = """\
    Python library that serves as an API for common \
    cryptographic primitives used to implement OPRF, OT, \
    and PSI protocols.\
    """
license = {text = "MIT"}
authors = [
    {name = "Nth Party"},
    {email = "team@nthparty.com"}
]
readme = "README.rst"
requires-python = ">=3.7"
dependencies = [
    "parts~=1.6",
    "fe25519~=1.4",
    "ge25519~=1.4",
    "bn254~=0.1"
]

[project.urls]
Repository = "https://github.com/nthparty/oblivious"
Documentation = "https://oblivious.readthedocs.io"

[project.optional-dependencies]
rbcl = [
    "rbcl~=1.0"
]
mclbn256 = [
    "mclbn256~=1.3"
]
docs = [
    "toml~=0.10.2",
    "sphinx~=4.2.0",
    "sphinx-rtd-theme~=1.0.0"
]
test = [
    "pytest~=7.2",
    "pytest-cov~=4.0",
    "bitlist~=1.1",
    "fountains~=2.1"
]
lint = [
    "pylint~=2.17.0"
]
coveralls = [
    "coveralls~=3.3.1"
]
publish = [
    "build~=0.10",
    "twine~=4.0"
]

[build-system]
requires = [
    "setuptools~=67.6"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--doctest-modules --ignore=docs --cov=oblivious --cov-report term-missing"
