name: lint-test-cover-docs
on:
  push
jobs:
  lint_test_cover_docs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
        xcl: ['omit', 'install']  # rbcl, mcl, etc. for Python bindings to a C library binary
    name: "Python ${{ matrix.python-version }}"
    steps:
      - uses: actions/checkout@v2
      - name: Install Python.
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install the optional rbcl and mcl packages and associated dependencies.
        run: |
          pip install -U .[rbcl,mcl]
        if: matrix.xcl == 'install'
      - name: Lint and test module.
        run: |
          pip install -U .[lint,test]
          python -m pylint src/oblivious test/test_ristretto.py test/test_bn254.py # Check against linting rules.
          python -m pytest # Run tests.
      - name: Publish coverage results.
        run: |
          pip install -U .[coveralls]
          python -m coveralls --service=github # Submit to coveralls.
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.8' && matrix.xcl == 'install'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test auto-generation of documentation.
        run: |
          pip install -U .[docs]
          cd docs && sphinx-apidoc -f -E --templatedir=_templates -o _source ../src && make html && cd ..