name: lint-test-cover-docs
on:
  push
jobs:
  lint_test_cover_docs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
        rbcl: ['omit', 'install']
    name: "Python ${{ matrix.python-version }}"
    steps:
      - uses: actions/checkout@v2
      - name: Install Python.
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install optional rbcl package.
        run: |
          pip install -U six~=1.16 cffi~=1.15 rbcl
        if: matrix.rbcl == 'install'
      - name: Lint and test module.
        run: |
          python setup.py requirements lint test && pip install -U . -r requirements.txt
          python -m pylint oblivious ./test/test_ristretto.py ./test/test_bn254.py # Check against linting rules.
          python -m pytest # Run tests.
      - name: Publish coverage results.
        run: |
          python setup.py requirements coveralls && pip install -U -r requirements.txt
          python -m coveralls --service=github # Submit to coveralls.
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.8' && matrix.rbcl == 'install'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test auto-generation of documentation.
        run: |
          python setup.py requirements docs && pip install -U -r requirements.txt
          cd docs && sphinx-apidoc -f -E --templatedir=_templates -o _source .. ../setup.py && make html && cd ..
